In [246]:
import pandas as pd

In [247]:
df=pd.read_csv('titanic.csv')
df.columns

Index(['pclass', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket', 'fare',
       'cabin', 'embarked', 'survived'],
      dtype='object')

In [248]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   pclass    1309 non-null   int64  
 1   name      1309 non-null   object 
 2   sex       1309 non-null   object 
 3   age       1046 non-null   float64
 4   sibsp     1309 non-null   int64  
 5   parch     1309 non-null   int64  
 6   ticket    1309 non-null   object 
 7   fare      1308 non-null   float64
 8   cabin     295 non-null    object 
 9   embarked  1307 non-null   object 
 10  survived  1309 non-null   int64  
dtypes: float64(2), int64(4), object(5)
memory usage: 112.6+ KB


In [249]:
df['fam_count']=df['sibsp']+df['parch']

In [250]:
df.head()

pclass                                             name     sex      age  \
0       1                    Allen, Miss. Elisabeth Walton  female  29.0000   
1       1                   Allison, Master. Hudson Trevor    male   0.9167   
2       1                     Allison, Miss. Helen Loraine  female   2.0000   
3       1             Allison, Mr. Hudson Joshua Creighton    male  30.0000   
4       1  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.0000   

   sibsp  parch  ticket      fare    cabin embarked  survived  fam_count  
0      0      0   24160  211.3375       B5        S         1          0  
1      1      2  113781  151.5500  C22 C26        S         1          3  
2      1      2  113781  151.5500  C22 C26        S         0          3  
3      1      2  113781  151.5500  C22 C26        S         0          3  
4      1      2  113781  151.5500  C22 C26        S         0          3

In [251]:
df=df.drop(columns=['sibsp','parch'])
df

pclass                                             name     sex  \
0          1                    Allen, Miss. Elisabeth Walton  female   
1          1                   Allison, Master. Hudson Trevor    male   
2          1                     Allison, Miss. Helen Loraine  female   
3          1             Allison, Mr. Hudson Joshua Creighton    male   
4          1  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   
...      ...                                              ...     ...   
1304       3                             Zabour, Miss. Hileni  female   
1305       3                            Zabour, Miss. Thamine  female   
1306       3                        Zakarian, Mr. Mapriededer    male   
1307       3                              Zakarian, Mr. Ortin    male   
1308       3                               Zimmerman, Mr. Leo    male   

          age  ticket      fare    cabin embarked  survived  fam_count  
0     29.0000   24160  211.3375       B5        S         1          0  
1      0.9167  113781  151.5500  C22 C26        S         1          3  
2      2.0000  113781  151.5500  C22 C26        S         0          3  
3     30.0000  113781  151.5500  C22 C26        S         0          3  
4     25.0000  113781  151.5500  C22 C26        S         0          3  
...       ...     ...       ...      ...      ...       ...        ...  
1304  14.5000    2665   14.4542      NaN        C         0          1  
1305      NaN    2665   14.4542      NaN        C         0          1  
1306  26.5000    2656    7.2250      NaN        C         0          0  
1307  27.0000    2670    7.2250      NaN        C         0          0  
1308  29.0000  315082    7.8750      NaN        S         0          0  

[1309 rows x 10 columns]

In [252]:
df['age']=df['age'].round(1)

In [253]:
df['fare']=df['fare'].round(1)

In [254]:
df['sex']=df['sex'].str.title()# str is an attribute which will help us to apply str built in methods it helps fetch sinngle single value

In [255]:
df=df.rename(columns={'sex':'gender'})# rename use to change the column
df

pclass                                             name  gender   age  \
0          1                    Allen, Miss. Elisabeth Walton  Female  29.0   
1          1                   Allison, Master. Hudson Trevor    Male   0.9   
2          1                     Allison, Miss. Helen Loraine  Female   2.0   
3          1             Allison, Mr. Hudson Joshua Creighton    Male  30.0   
4          1  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  Female  25.0   
...      ...                                              ...     ...   ...   
1304       3                             Zabour, Miss. Hileni  Female  14.5   
1305       3                            Zabour, Miss. Thamine  Female   NaN   
1306       3                        Zakarian, Mr. Mapriededer    Male  26.5   
1307       3                              Zakarian, Mr. Ortin    Male  27.0   
1308       3                               Zimmerman, Mr. Leo    Male  29.0   

      ticket   fare    cabin embarked  survived  fam_count  
0      24160  211.3       B5        S         1          0  
1     113781  151.6  C22 C26        S         1          3  
2     113781  151.6  C22 C26        S         0          3  
3     113781  151.6  C22 C26        S         0          3  
4     113781  151.6  C22 C26        S         0          3  
...      ...    ...      ...      ...       ...        ...  
1304    2665   14.5      NaN        C         0          1  
1305    2665   14.5      NaN        C         0          1  
1306    2656    7.2      NaN        C         0          0  
1307    2670    7.2      NaN        C         0          0  
1308  315082    7.9      NaN        S         0          0  

[1309 rows x 10 columns]

In [256]:
df['embarked']=df['embarked'].replace({'S':'Southampton','C':'Cherbourg','Q':'Queestown'})# to replace values
df

pclass                                             name  gender   age  \
0          1                    Allen, Miss. Elisabeth Walton  Female  29.0   
1          1                   Allison, Master. Hudson Trevor    Male   0.9   
2          1                     Allison, Miss. Helen Loraine  Female   2.0   
3          1             Allison, Mr. Hudson Joshua Creighton    Male  30.0   
4          1  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  Female  25.0   
...      ...                                              ...     ...   ...   
1304       3                             Zabour, Miss. Hileni  Female  14.5   
1305       3                            Zabour, Miss. Thamine  Female   NaN   
1306       3                        Zakarian, Mr. Mapriededer    Male  26.5   
1307       3                              Zakarian, Mr. Ortin    Male  27.0   
1308       3                               Zimmerman, Mr. Leo    Male  29.0   

      ticket   fare    cabin     embarked  survived  fam_count  
0      24160  211.3       B5  Southampton         1          0  
1     113781  151.6  C22 C26  Southampton         1          3  
2     113781  151.6  C22 C26  Southampton         0          3  
3     113781  151.6  C22 C26  Southampton         0          3  
4     113781  151.6  C22 C26  Southampton         0          3  
...      ...    ...      ...          ...       ...        ...  
1304    2665   14.5      NaN    Cherbourg         0          1  
1305    2665   14.5      NaN    Cherbourg         0          1  
1306    2656    7.2      NaN    Cherbourg         0          0  
1307    2670    7.2      NaN    Cherbourg         0          0  
1308  315082    7.9      NaN  Southampton         0          0  

[1309 rows x 10 columns]

In [257]:
df[['lname','temp']]=df['name'].str.split(',',expand=True)
df[['title','fname']]=df['temp'].str.split('.',expand=True,n=1)
df=df.drop(columns=['name','temp'])
for col in ['lname','fname','title']:
    df[col].str.strip()


In [258]:
for col in ['lname','fname','title']:
    df[col]=df[col].str.strip()
df

pclass  gender   age  ticket   fare    cabin     embarked  survived  \
0          1  Female  29.0   24160  211.3       B5  Southampton         1   
1          1    Male   0.9  113781  151.6  C22 C26  Southampton         1   
2          1  Female   2.0  113781  151.6  C22 C26  Southampton         0   
3          1    Male  30.0  113781  151.6  C22 C26  Southampton         0   
4          1  Female  25.0  113781  151.6  C22 C26  Southampton         0   
...      ...     ...   ...     ...    ...      ...          ...       ...   
1304       3  Female  14.5    2665   14.5      NaN    Cherbourg         0   
1305       3  Female   NaN    2665   14.5      NaN    Cherbourg         0   
1306       3    Male  26.5    2656    7.2      NaN    Cherbourg         0   
1307       3    Male  27.0    2670    7.2      NaN    Cherbourg         0   
1308       3    Male  29.0  315082    7.9      NaN  Southampton         0   

      fam_count      lname   title                              fname  
0             0      Allen    Miss                   Elisabeth Walton  
1             3    Allison  Master                      Hudson Trevor  
2             3    Allison    Miss                      Helen Loraine  
3             3    Allison      Mr            Hudson Joshua Creighton  
4             3    Allison     Mrs  Hudson J C (Bessie Waldo Daniels)  
...         ...        ...     ...                                ...  
1304          1     Zabour    Miss                             Hileni  
1305          1     Zabour    Miss                            Thamine  
1306          0   Zakarian      Mr                        Mapriededer  
1307          0   Zakarian      Mr                              Ortin  
1308          0  Zimmerman      Mr                                Leo  

[1309 rows x 12 columns]

In [259]:
ticket_cnt=df['ticket'].value_counts()# it acts like aggreagate function that ticket  is index values are the vales for index
# return type is series

In [260]:
ticket_cnt=ticket_cnt.reset_index() # data frame

In [261]:
df=pd.merge(df,ticket_cnt,'inner',on='ticket')#pd.merge(lefttab,right tab,how='inner',on='colname')
df

pclass  gender   age  ticket   fare    cabin     embarked  survived  \
0          1  Female  29.0   24160  211.3       B5  Southampton         1   
1          1    Male   0.9  113781  151.6  C22 C26  Southampton         1   
2          1  Female   2.0  113781  151.6  C22 C26  Southampton         0   
3          1    Male  30.0  113781  151.6  C22 C26  Southampton         0   
4          1  Female  25.0  113781  151.6  C22 C26  Southampton         0   
...      ...     ...   ...     ...    ...      ...          ...       ...   
1304       3  Female  14.5    2665   14.5      NaN    Cherbourg         0   
1305       3  Female   NaN    2665   14.5      NaN    Cherbourg         0   
1306       3    Male  26.5    2656    7.2      NaN    Cherbourg         0   
1307       3    Male  27.0    2670    7.2      NaN    Cherbourg         0   
1308       3    Male  29.0  315082    7.9      NaN  Southampton         0   

      fam_count      lname   title                              fname  count  
0             0      Allen    Miss                   Elisabeth Walton      4  
1             3    Allison  Master                      Hudson Trevor      6  
2             3    Allison    Miss                      Helen Loraine      6  
3             3    Allison      Mr            Hudson Joshua Creighton      6  
4             3    Allison     Mrs  Hudson J C (Bessie Waldo Daniels)      6  
...         ...        ...     ...                                ...    ...  
1304          1     Zabour    Miss                             Hileni      2  
1305          1     Zabour    Miss                            Thamine      2  
1306          0   Zakarian      Mr                        Mapriededer      1  
1307          0   Zakarian      Mr                              Ortin      1  
1308          0  Zimmerman      Mr                                Leo      1  

[1309 rows x 13 columns]

In [262]:
df=df.rename(columns={'count':'passenger_cnt'})
df.columns

Index(['pclass', 'gender', 'age', 'ticket', 'fare', 'cabin', 'embarked',
       'survived', 'fam_count', 'lname', 'title', 'fname', 'passenger_cnt'],
      dtype='object')

In [263]:
l=['ticket','title','fname','lname','gender', 'age','embarked','fam_count','passenger_cnt','pclass', 'fare', 'survived']
df=df[l]

In [264]:
df['fname']=='Emil'
df.loc[df['fname']=='Emil']

ticket title fname       lname gender   age     embarked  fam_count  \
39   PC 17591    Mr  Emil    Brandeis   Male  48.0    Cherbourg          0   
290    110413    Mr  Emil     Taussig   Male  52.0  Southampton          2   
715    343276    Mr  Emil  Christmann   Male  29.0  Southampton          0   

     passenger_cnt  pclass  fare  survived  
39               1       1  50.5         0  
290              3       1  79.6         0  
715              1       3   8.0         0

In [265]:
df.loc[ (df['fname']=="Emil") & (df['age']==29.0)]

ticket title fname       lname gender   age     embarked  fam_count  \
715  343276    Mr  Emil  Christmann   Male  29.0  Southampton          0   

     passenger_cnt  pclass  fare  survived  
715              1       3   8.0         0

get the details of psgs whose ticket is 110413 or 343276

In [266]:
df.loc[ (df['ticket']=='343276') | (df['ticket']=='110413')]

df.loc[ df['ticket'].isin( ['343276','110413'] ) ]

ticket title                     fname       lname  gender   age  \
289  110413  Miss                      Ruth     Taussig  Female  18.0   
290  110413    Mr                      Emil     Taussig    Male  52.0   
291  110413   Mrs  Emil (Tillie Mandelbaum)     Taussig  Female  39.0   
715  343276    Mr                      Emil  Christmann    Male  29.0   

        embarked  fam_count  passenger_cnt  pclass  fare  survived  
289  Southampton          2              3       1  79.6         1  
290  Southampton          2              3       1  79.6         0  
291  Southampton          2              3       1  79.6         1  
715  Southampton          0              1       3   8.0         0

In [267]:
df.agg({'fare':['count','max','min','sum','mean']})

fare
count   1308.000000
max      512.300000
min        0.000000
sum    43553.400000
mean      33.297706

In [268]:
df.loc[df['fare']==0].shape

(17, 12)

In [269]:
df.loc[df['fare']==0].reset_index()

index  ticket     title                    fname       lname gender   age  \
0       7  112050        Mr                Thomas Jr     Andrews   Male  39.0   
1      70  112051        Mr  Roderick Robert Crispin    Chisholm   Male   NaN   
2     125  112058        Mr                  Richard         Fry   Male   NaN   
3     150  112059        Mr                  William    Harrison   Male  40.0   
4     170  112058        Mr             Joseph Bruce       Ismay   Male  49.0   
5     223  112052        Mr      William Henry Marsh        Parr   Male   NaN   
6     234   19972  Jonkheer              John George    Reuchlin   Male  38.0   
7     363  239853        Mr                  William    Campbell   Male   NaN   
8     384  239853        Mr           Alfred Fleming  Cunningham   Male   NaN   
9     410  239854        Mr    Anthony Wood "Archie"       Frost   Male   NaN   
10    473  239855        Mr                 Robert J      Knight   Male   NaN   
11    528  239853        Mr          Francis "Frank"      Parkes   Male   NaN   
12    581  239856        Mr           Ennis Hastings      Watson   Male   NaN   
13    896    LINE        Mr                   Alfred     Johnson   Male  49.0   
14    898    LINE        Mr       William Cahoone Jr     Johnson   Male  19.0   
15    963    LINE        Mr                   Lionel     Leonard   Male  36.0   
16   1254    LINE        Mr            William Henry   Tornquist   Male  25.0   

       embarked  fam_count  passenger_cnt  pclass  fare  survived  
0   Southampton          0              1       1   0.0         0  
1   Southampton          0              1       1   0.0         0  
2   Southampton          0              2       1   0.0         0  
3   Southampton          0              1       1   0.0         0  
4   Southampton          0              2       1   0.0         1  
5   Southampton          0              1       1   0.0         0  
6   Southampton          0              1       1   0.0         0  
7   Southampton          0              3       2   0.0         0  
8   Southampton          0              3       2   0.0         0  
9   Southampton          0              1       2   0.0         0  
10  Southampton          0              1       2   0.0         0  
11  Southampton          0              3       2   0.0         0  
12  Southampton          0              1       2   0.0         0  
13  Southampton          0              4       3   0.0         0  
14  Southampton          0              4       3   0.0         0  
15  Southampton          0              4       3   0.0         0  
16  Southampton          0              4       3   0.0         1

In [270]:
crew_members = df.loc[df['fare']==0].reset_index(drop=True)

df=df.loc[df['fare']!=0].reset_index(drop=True)

df.loc[df['fare']==0].shape

(0, 12)